/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.projet;

/**
 *
 * @author Aurélie
 */
public class project_detail extends javax.swing.JFrame {

    /**
     * Creates new form project_detail
     */
    public project_detail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameText = new javax.swing.JTextField();
        estimatedText = new javax.swing.JTextField();
        finalText = new javax.swing.JTextField();
        StatusText = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        start = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        cancel2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameText.setBorder(null);
        nameText.setOpaque(false);
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 560, 50));

        estimatedText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        estimatedText.setBorder(null);
        estimatedText.setOpaque(false);
        estimatedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedTextActionPerformed(evt);
            }
        });
        getContentPane().add(estimatedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 240, 50));

        finalText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        finalText.setBorder(null);
        finalText.setOpaque(false);
        finalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalTextActionPerformed(evt);
            }
        });
        getContentPane().add(finalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 140, 50));

        StatusText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StatusText.setBorder(null);
        StatusText.setOpaque(false);
        StatusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTextActionPerformed(evt);
            }
        });
        getContentPane().add(StatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 160, 50));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "secondes", "minutes", "heures", "jours", "semaines", "mois", "années" }));
        jComboBox1.setBorder(null);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 150, 50));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion_de_projet/images/Start.png"))); // NOI18N
        start.setActionCommand("");
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 170, 70));

        cancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion_de_projet/images/Cancel.png"))); // NOI18N
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 170, 70));

        cancel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion_de_projet/images/validate.png"))); // NOI18N
        getContentPane().add(cancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, 170, 70));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion_de_projet/images/Cancel.png"))); // NOI18N
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 700, 170, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion_de_projet/images/project-detail.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void estimatedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimatedTextActionPerformed

    private void finalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalTextActionPerformed

    private void StatusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField StatusText;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    private javax.swing.JTextField estimatedText;
    private javax.swing.JTextField finalText;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
