/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.projet;

/**
 *
 * @author Aurélie
 */
public class Tech_Skills extends javax.swing.JFrame {

    /**
     * Creates new form Tech_Skills
     */
    public Tech_Skills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        techText = new javax.swing.JTextField();
        skillsText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        techText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        techText.setBorder(null);
        techText.setOpaque(false);
        techText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techTextActionPerformed(evt);
            }
        });
        getContentPane().add(techText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 560, 50));

        skillsText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        skillsText.setToolTipText("");
        skillsText.setBorder(null);
        skillsText.setOpaque(false);
        skillsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillsTextActionPerformed(evt);
            }
        });
        getContentPane().add(skillsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 870, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion_de_projet/images/Tech-skills.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void techTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_techTextActionPerformed

    private void skillsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skillsTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tech_Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tech_Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tech_Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tech_Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tech_Skills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField skillsText;
    private javax.swing.JTextField techText;
    // End of variables declaration//GEN-END:variables
}
